trigger:
  branches:
    include:
      - adf_publish

pool:
  name: SelfPool   # <-- replace with your exact agent pool name

steps:
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.SourcesDirectory)'
    artifactName: 'adf_drop'